#! /bin/bash

echo "Destroying existing box without confirmation"
vagrant destroy --force
echo "Removing existing Vagrantfile"
rm -f Vagrantfile
echo "Creating a new Vagrantfile"
vagrant init ubuntu/xenial64
echo "Saving the Vagrantfile to Vagrantfile.vanilla"
cp Vagrantfile Vagrantfile.vanilla
echo "Bringing up the base box"
vagrant up --provider virtualbox
vagrant global-status
