#! /bin/bash

vagrant halt
vagrant halt
vagrant global-status
echo "Destroying existing box without confirmation"
vagrant destroy --force
echo "Removing existing Vagrantfile"
rm -f Vagrantfile
echo "Creating a new Vagrantfile"
# switching from bento to ubuntu for the base box
# there are way too many open issues with bento, some of which other Hack Oregonians have
# encountered.
vagrant init bento/ubuntu-16.04
echo "Saving the Vagrantfile to Vagrantfile.bento"
cp Vagrantfile Vagrantfile.bento
echo "Bringing up the base box"
vagrant up --provider virtualbox
vagrant global-status
