#! /bin/bash

# Most Ubuntu systems I've looked at have 'git' and 'vim' installed already.
# But Linux Mint Sarah doesn't. So here they are.
sudo apt-get install -y \
  git \
  vim-nox \
  > 0gitvim.log 2>&1
