#! /bin/bash

# sync package repo metadata
sudo apt update

# upgrade any packages that need it
sudo apt upgrade -y

# install the core packages
sudo apt install -y \
  apt-file \
  aria2 \
  curl \
  git \
  lynx \
  vim-nox \
  virtualenvwrapper \
  wget

# run apt-file update
sudo apt-file update

# set vim as default editor
sudo cp set-editor.bash /etc/profile.d/

echo "Log out and back in to set required environment variables!"
