#! /bin/bash

echo "installing the core packages"
sudo apt-get install -y \
  apt-file \
  build-essential \
  cpu-checker \
  debconf-utils \
  curl \
  dkms \
  gdebi-core \
  linux-headers-$(uname -r) \
  wget \
  > 1core.log 2>&1

echo "updating the apt-file index"
sudo apt-file update > /dev/null 2>&1

echo "capturing the installer script"
# seems to be empty on Linux Mint Sarah
sudo debconf-get-selections --installer > ~/debconf-selections.txt
