#! /bin/bash

echo "syncing package repo metadata - this may take some time"
sudo apt-get update

echo "upgrading any packages that need it - this may take some time"
sudo apt-get upgrade -y

echo "installing the core packages"
sudo apt-get install -qqy \
  apt-file \
  build-essential \
  cpu-checker \
  debconf-utils \
  curl \
  dkms \
  gdebi-core \
  linux-headers-$(uname -r) \
  wget \
  > 1core.log 2>&1

echo "updating the apt-file index"
sudo apt-file update > /dev/null 2>&1
