#! /bin/bash

echo "Installing database and GIS service packages"
sudo apt-get install -y \
  postgresql-9.5 \
  postgresql-client-9.5 \
  postgresql-contrib-9.5 \
  postgresql-doc-9.5 \
  postgis \
  postgis-doc \
  postgresql-9.5-pgrouting \
  postgresql-9.5-pgrouting-doc \
  postgresql-9.5-postgis-2.2 \
  postgresql-9.5-postgis-scripts \
  postgresql-plpython3-9.5 \
  > database-gis-services.log 2>&1

# make yourself a PostgreSQL superuser
sudo su -c "createuser -s ${USER}" postgres
echo "You are now a PostgreSQL super-user with ID '${USER}'!"
