#! /bin/bash

# LaTeX packages for PDF notebook downloads
# File an issue at https://github.com/hackoregon/linux-laptop-setup/issues/new if you need others
sudo apt-get install -qqy \
  pandoc \
  pandoc-citeproc \
  texlive-latex-base \
  texlive-fonts-recommended \
  texlive-latex-recommended \
  texlive-latex-extra \
  texlive-generic-recommended

# use US letter paper size
sudo paperconfig -p letter
sudo tl-paper set all letter

# what machine have we got?
if [ `arch` == "x86_64" ]
then
  export ARCH=64
  export TAG=x86_64
else
  export ARCH=32
  export TAG=x86
fi

echo "Your machine is ${ARCH} bits."
echo "Downloading the Miniconda3 installer to $HOME/Downloads."
echo ""

# http://conda.pydata.org/miniconda.html
echo "Making sure $HOME/Downloads exists."
mkdir -p $HOME/Downloads

pushd $HOME/Downloads
echo "Removing any old Miniconda3 installers."
rm -f Miniconda3*
echo "Downloading the latest Miniconda3 installer."
wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-$TAG.sh
echo "Download is finished."
popd

echo "Removing any existing Miniconda3 installation!"
rm -fr $HOME/miniconda3
echo ""
echo "Ready to install Miniconda3 - please read *all* the instructions below carefully before"
echo "starting!"
echo ""
echo "1. At the first '>>>' prompt, press 'Enter'. Page through the license with the"
echo "   space bar."
echo "2. When you get the next '>>>' prompt, enter 'yes' to approve the license terms."
echo "3. At the next '>>>', press 'Enter' to confirm the default install location."
echo ""
echo "The install will start. When it is finished, you'll be asked if you want to"
echo "prepend the Miniconda3 location to your PATH. The default is 'no'. Press"
echo "'Enter' to accept the default. Do *not* enter 'yes'! Doing so will break"
echo "your system!"
echo ""
echo "The installer will close its window when it finishes."
echo ""

# go for it!
COMMAND="bash $HOME/Downloads/Miniconda3-latest-Linux-$TAG.sh"
echo "Press 'Enter' when you're ready to install Miniconda3."
read DUMMY
x-terminal-emulator -e $COMMAND

echo "Press 'Enter' here when the install has finished and closed the other terminal."
read DUMMY

# make sure everything's there for the data science students
echo ""
echo "Updating the Miniconda distribution."
~/miniconda3/bin/conda update --yes --all

echo "Creating a Conda environment named 'data-science' with 'jupyter', 'seaborn', "
echo "'statsmodels' and 'scikit-learn'."
~/miniconda3/bin/conda create --yes --name data-science jupyter seaborn statsmodels scikit-learn

echo ""
echo "Adding the data science activate and deactivate aliases to your '.bashrc' file."
cat data-science-aliases >> $HOME/.bashrc

echo ""
echo "To use the data science services, open a terminal and type"
echo ""
echo "activate-data-science"
echo "jupyter notebook"
echo ""
echo "A browser will open to your Jupyter notebook."
