#! /bin/bash

# LaTeX packages for PDF notebook downloads
# File an issue at https://github.com/hackoregon/linux-laptop-setup/issues/new if you need others
echo "Installing LaTeX packages for notebook PDF downloads"
sudo apt-get install -qqy \
  pandoc \
  pandoc-citeproc \
  texlive-latex-base \
  texlive-fonts-recommended \
  texlive-latex-recommended \
  texlive-latex-extra \
  texlive-generic-recommended \
  > data-science-services.log 2>&1

echo "Configuring paper size to letter"
sudo paperconfig -p letter
sudo tl-paper set all letter

# what machine have we got?
if [ `arch` == "x86_64" ]
then
  export ARCH=64
  export TAG=x86_64
else
  export ARCH=32
  export TAG=x86
fi

echo "Your machine is ${ARCH} bits."
echo ""

# http://conda.pydata.org/miniconda.html
echo "Making sure $HOME/Downloads exists."
mkdir -p $HOME/Downloads

pushd $HOME/Downloads
echo "Removing any old Miniconda3 installers."
rm -f Miniconda3*
echo "Downloading the latest Miniconda3 installer."
wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-$TAG.sh
echo "Download is finished."
popd

echo "Ready to install Miniconda3. Notes:"
echo ""
echo "1. This is a batch install using all the defaults. License approval on your part is assumed."
echo "2. The installer will not overwrite an existing Miniconda3 installation."
echo ""
echo "Press 'Enter' when you're ready to install Miniconda3."
read DUMMY

# go for it!
bash $HOME/Downloads/Miniconda3-latest-Linux-$TAG.sh -b

# make sure everything's there for the data science students
echo ""
echo "Updating the Miniconda distribution."
~/miniconda3/bin/conda update --yes --all

echo "Creating a Conda environment named 'data-science' with 'jupyter', 'seaborn', "
echo "'statsmodels' and 'scikit-learn'."
~/miniconda3/bin/conda create --yes --name data-science jupyter seaborn statsmodels scikit-learn

echo ""
echo "Adding the data science activate and deactivate aliases to your '.bashrc' file."
cat data-science-aliases >> $HOME/.bashrc

echo ""
echo "To use the data science services, open a terminal and type"
echo ""
echo "activate-data-science"
echo "jupyter notebook"
echo ""
echo "A browser will open to your Jupyter notebook."
