#! /bin/bash

echo "Installing Docker packages"
sudo apt-get install -y \
  apparmor \
  aufs-tools \
  cgroupfs-mount \
  debootstrap \
  docker.io \
  docker-doc \
  rinse \
  ubuntu-fan \
  zfs-fuse \
  > docker-hosting.log 2>&1

sudo gpasswd -a ${USER} docker && sudo systemctl restart docker
echo "Log out and back in to join the 'docker' group!"
