#! /bin/bash

# upstream repository
# https://docs.docker.com/engine/installation/linux/ubuntulinux/
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 \
  --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo cp docker.list /etc/apt/sources.list.d/
sudo apt update && sudo apt-file update

sudo apt install -y \
  aufs-tools \
  cgroupfs-mount \
  docker-engine \
  linux-image-extra-$(uname -r)

sudo gpasswd -a ${USER} docker && sudo systemctl restart docker
