#! /bin/bash -v

# Packages
./postgres
sudo apt-get install -y \
  postgis \
  postgis-doc \
  postgresql-9.5-pgrouting \
  postgresql-9.5-pgrouting-doc \
  postgresql-9.5-postgis-2.2 \
  postgresql-9.5-postgis-scripts \
  grass \
  grass-doc \
  grass-gui \
  qgis \
  qgis-api-doc \
  proj-bin \
  gdal-bin \
  qgis-server \
  qgis-provider-grass \
  qgis-plugin-globe
