#! /bin/bash

echo "Adding the Git LFS repository"
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt-get update > /dev/null && sudo apt-file update > /dev/null

echo "Installing Git LFS"
sudo apt-get install -qqy git-lfs > /dev/null
