#! /bin/bash

# install the repository
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt-get update && sudo apt-file update
echo "https://packagecloud.io/github/git-lfs/linuxmint/ repository added!"
echo "https://packagecloud.io/github/git-lfs/linuxmint/ repository added!"

# install the package
sudo apt-get install -qqy git-lfs
