#! /bin/bash

# install the repository
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash

# sync package repo metadata
sudo apt update

# install the package
sudo apt install -y git-lfs
