#! /bin/bash

# LaTeX packages for PDF notebook downloads
# File an issue at https://github.com/hackoregon/linux-laptop-setup/issues/new if you need others
sudo apt-get install -y \
  pandoc \
  pandoc-citeproc \
  texlive-latex-base \
  texlive-fonts-recommended \
  texlive-latex-recommended \
  texlive-latex-extra \
  texlive-generic-recommended

# use US letter paper size
sudo paperconfig -p letter
sudo tl-paper set all letter

# Jupyter itself
source ${VIRTUALENVWRAPPER_SCRIPT}
rmvirtualenv jupyter
mkvirtualenv -p /usr/bin/python3 jupyter
workon jupyter

pip install --upgrade pip
pip install jupyter
pip install virtualenvwrapper
pip install scikit-learn
pip install seaborn

# IPyParallel
pip install ipyparallel
mkdir -p ~/.ipython/profile_default

# extensions
# see https://github.com/ipython/ipyparallel/issues/170
jupyter serverextension enable --py ipyparallel --user
jupyter nbextension install --py ipyparallel --user 
jupyter nbextension enable --py ipyparallel --user
