#! /bin/bash -v

# Packages
sudo apt-get install -y \
  pgadmin3 \
  postgresql \
  postgresql-client \
  postgresql-contrib \
  postgresql-doc

# create a PostgreSQL login / database
COMMAND="createuser -s ${USER}"
sudo su - postgres -c "${COMMAND}"
createdb ${USER}
