#! /bin/bash

# Packages
sudo apt-get install -y \
  postgresql \
  postgresql-client \
  postgresql-contrib \
  postgresql-doc \
  postgis \
  postgis-doc \
  postgresql-9.5-pgrouting \
  postgresql-9.5-pgrouting-doc

# make yourself a PostgreSQL superuser
sudo su -c "createuser -s ${USER}" postgres
echo "You are now a PostgreSQL super-user with ID '${USER}'!"
