#! /bin/bash

## symbols
source rstudio-symbols

## get into neutral territory, since we're root
sudo mkdir -p /usr/local/src
pushd /usr/local/src

## install RStudio® Server
## https://www.rstudio.com/about/trademark/
export PACKAGE=`echo ${SERVER}|sed 's;^.*rstudio-;rstudio-;'`
sudo rm -f ${PACKAGE}
echo "Downloading RStudio Server binary package"
sudo wget -q ${SERVER}
sudo gdebi --non-interactive ${PACKAGE}

popd
