#! /bin/bash

## symbols
source rstudio-symbols

## get into neutral territory, since we're root
sudo mkdir -p /usr/local/src
pushd /usr/local/src

## install RStudio® Server
## https://www.rstudio.com/about/trademark/
export PACKAGE=`echo ${SERVER}|sed 's;^.*rstudio-;rstudio-;'`
sudo rm -f ${PACKAGE}
echo "Downloading RStudio Server binary package"
sudo wget -q ${SERVER}
sudo gdebi --non-interactive ${PACKAGE}

popd

# show IP address
ifconfig
echo "See 'ifconfig' output above for your IP address"

# listen on 0.0.0.0:8888, don't start a browser!
jupyter notebook --port=8888 --ip=0.0.0.0 --no-browser
