#! /bin/bash

## symbols
source rstudio-symbols

## get into neutral territory, since we're root
sudo mkdir -p /usr/local/src
pushd /usr/local/src

## install RStudio® Desktop
## https://www.rstudio.com/about/trademark/
export PACKAGE=`echo ${DESKTOP}|sed 's;^.*rstudio-;rstudio-;'`
sudo rm -f ${PACKAGE}
echo "Downloading RStudio Desktop binary package"
sudo wget -q ${DESKTOP}
sudo gdebi --non-interactive ${PACKAGE}

popd
