#! /bin/bash

source ${VIRTUALENVWRAPPER_SCRIPT}
workon jupyter

# show IP address
ifconfig
echo "See 'ifconfig' output above for your IP address"

# listen on 0.0.0.0:8888, don't start a browser!
jupyter notebook --port=8888 --ip=0.0.0.0 --no-browser
