#! /bin/bash

# add the Oracle repository and key
sudo cp virtualbox.list /etc/apt/sources.list.d/
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
sudo apt-get update && sudo apt-file update

# install VirtualBox
sudo apt install -y virtualbox-5.1

# join the group
sudo gpasswd -a ${USER} vboxusers

# what machine have we got?
if [ `arch` == "x86_64" ]
then
  export ARCH=64
else
  export ARCH=32
fi
echo  "Your machine is ${ARCH} bits."

echo "You will need to install Vagrant from the Hashicorp website."
echo "1. Browse to 'https://www.vagrantup.com/downloads.html'."
echo "2. Find the link to the Debian package for ${ARCH}-bit systems."
echo "3. Click the link to open it with the GDebi package installer. This should be the browser default."
echo "4. Press the 'Install' button. You may have to enter your password."
echo "5. Close the GDebi window after the install finishes."
echo ""
echo "Press 'Enter' when the install has finished."
read DUMMY
echo "Log out and back in to join the 'vboxusers' group!"
