#! /bin/bash

# add the Oracle repository and key
sudo cp virtualbox.list /etc/apt/sources.list.d/
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
sudo apt-get update && sudo apt-file update

# install VirtualBox
sudo apt install -y virtualbox-5.1

# join the group
sudo gpasswd -a ${USER} vboxusers

# what machine have we got?
if [ `arch` == "x86_64" ]
then
  export ARCH=64
else
  export ARCH=32
fi
echo  "Your machine is ${ARCH} bits."

echo "You will need to install Vagrant from the Hashicorp website."
echo ""
echo "1. Browse to 'https://www.vagrantup.com/downloads.html'."
echo "2. Find the link to the Debian package for ${ARCH}-bit systems."
echo "3. Click the link to open it with the GDebi package installer."
echo "   This should be the browser default."
echo "4. You may get a dialog box about an older version being available in a"
echo "   software channel. If you do, press the 'Close' button."
echo "   Hack Oregon Vagrant boxes won't work with older versions of Vagrant!"
echo "5. Press the 'Install Package' button."
echo "   You may get a dialog box about granting administrative rights."
echo "   If you do, enter your password and press 'OK'."
echo "6. When the install finishes, press the 'Close' button."
echo "   Then close the GDebi window."
echo ""
echo "Press 'Enter' when the install has finished."
read DUMMY
echo "Log out and back in to join the 'vboxusers' group!"
