#! /bin/bash

echo "Installing VirtualBox and Vagrant from Linux Mint repositories"
sudo apt-get install -qqy \
  vagrant \
  virtualbox \
  virtualbox-dkms \
  virtualbox-ext-pack \
  virtualbox-guest-additions-iso \
  virtualbox-qt

echo "updating the apt-file index"
sudo apt-file update > /dev/null

# join the group
sudo gpasswd -a ${USER} vboxusers
echo "Log out and back in to join the 'vboxusers' group!"
