#! /bin/bash

vagrant halt
vagrant halt
vagrant global-status
echo "Destroying existing box without confirmation"
vagrant destroy --force
echo "Removing existing Vagrantfile"
rm -f Vagrantfile
echo "Creating a new Vagrantfile"
cp Vagrantfile.hackoregon Vagrantfile
echo "Bringing up the Hack Oregon box"
vagrant up --provider virtualbox
vagrant global-status
