#! /bin/bash

echo "Entering the Vagrant box execution directory"
export HERE=`pwd`
cd ../vagrant-box-execution
echo "Destroying existing box without confirmation - you can ignore any errors"
vagrant destroy --force
echo "Removing existing Vagrantfile"
rm -f Vagrantfile
echo "Creating a new Vagrantfile"
# switching from bento to ubuntu for the base box
# there are way too many open issues with bento, some of which other Hack Oregonians have
# encountered.
vagrant init bento/ubuntu-16.04
echo "Saving the Vagrantfile to Vagrantfile.bento"
cp Vagrantfile $HERE/Vagrantfile.bento
echo ""
echo ""
echo "To log into the Vagrant box, type"
echo ""
echo "cd ../vagrant-box-execution"
echo "vagrant up"
echo "vagrant ssh"
