#! /bin/bash

# https://www.vagrantup.com/docs/virtualbox/boxes.html
/usr/bin/time vagrant package --base "Hack Oregon Base" --output hackoregon-base.box
# $ ./package 
# ==> Hack Oregon Base: Exporting VM...
# ==> Hack Oregon Base: Compressing package to: /home/znmeb/Projects/linux-laptop-setup/vagrant-box-creation/hackoregon-base.box
# 65.24user 12.93system 21:48.35elapsed 5%CPU (0avgtext+0avgdata 36780maxresident)k
# 0inputs+1442648outputs (0major+94994minor)pagefaults 0swaps

mkdir -p ~/Downloads
mv hackoregon-base.box ~/Downloads/
