#! /bin/bash

# Make a Ubuntu server suitable for Vagrant
# https://www.vagrantup.com/docs/boxes/base.html
# https://www.vagrantup.com/docs/virtualbox/boxes.html

echo "First, create the 'vagrant' user if necessary. This will error if user exists."
echo "You can ignore the error."
sudo useradd -c "Vagrant user" -G sudo -m -U vagrant
echo "Set default passwords for 'vagrant' and 'root'."
echo "root:vagrant" | sudo chpasswd
echo "vagrant:vagrant" | sudo chpasswd
echo "Create the '/vagrant' mount point."
sudo mkdir -p /vagrant
sudo chown vagrant:vagrant /vagrant
echo "Create your secure shell keys. Press 'Enter' for all prompts in the key generation."
ssh-keygen
echo "Install the Vagrant insecure keys"
pushd ~/.ssh
wget -q https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant
wget -q https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub
cp vagrant.pub authorized_keys
chmod 0600 authorized_keys
chmod 0600 vagrant
chmod 0644 vagrant.pub
popd
echo "You will be using the 'nano' editor in the final two steps. Just type the lines you need"
echo "to type and then exit with `CTL-O`, `Enter`, `CTL-X`."
echo ""
echo "Add the line 'UseDNS no' to the bottom of the file '/etc/ssh/sshd_config'."
sleep 10
sudo nano /etc/ssh/sshd_config
echo "Add the line 'vagrant ALL=(ALL:ALL) NOPASSWD: ALL' to the bottom of the file with 'visudo'."
sleep 10
sudo visudo
echo "All done!"
