#! /bin/bash

# https://www.vagrantup.com/docs/boxes/base.html
echo "Removing any existing 'hackoregon' box"
vagrant box remove hackoregon
vagrant box list
echo "Adding the box package 'hackoregon-base.box' as machine 'hackoregon'"
/usr/bin/time vagrant box add hackoregon ~/Downloads/hackoregon-base.box
# Adding the box package 'hackoregon-base.box' as machine 'hackoregon'
# ==> box: Box file was not detected as metadata. Adding it directly...
# ==> box: Adding box 'hackoregon' (v0) for provider: 
#     box: Unpacking necessary files from: file:///home/znmeb/Downloads/hackoregon-base.box
# ==> box: Successfully added box 'hackoregon' (v0) for 'virtualbox'!
# 9.08user 3.38system 1:52.01elapsed 11%CPU (0avgtext+0avgdata 40136maxresident)k
# 0inputs+2914536outputs (0major+20209minor)pagefaults 0swaps
echo "Removing any existing Vagrantfile"
rm -f Vagrantfile
echo "Creating a Vagrantfile"
vagrant init hackoregon
echo "Edit the Vagrantfile to add port forwarding"
vim Vagrantfile
# save copy of Vagrantfile
cp Vagrantfile ../vagrant-box-creation/Vagrantfile.hackoregon
echo "Bringing the box up"
vagrant up --provision
