#! /bin/bash

# add repository for latest R
sudo cp cran-ubuntu.list /etc/apt/sources.list.d
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
sudo apt update && sudo apt-file update

# Packages
sudo apt install -y \
  default-java-plugin \
  default-jdk \
  default-jre \
  gdebi \
  libcurl4-openssl-dev \
  libssh2-1-dev \
  libssl-dev \
  libxml2-dev \
  lmodern \
  pandoc \
  pandoc-citeproc \
  r-base \
  r-base-dev \
  texinfo \
  texlive-fonts-recommended \
  texlive-generic-recommended \
  texlive-latex-base \
  texlive-latex-extra \
  texlive-latex-recommended  \
  texlive-xetex  \
  xindy

## Upstream Calibre
sudo -v && \
  wget -nv -O- \
    https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py \
  | sudo python -c \
    "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"

# use US letter paper size
sudo paperconfig -p letter
sudo tl-paper set all letter

# R package installs need TMPDIR on "hard drive"
sudo mkdir -p /TMPDIR
sudo chmod a+rwx /TMPDIR
sudo cp Rprofile.site `R RHOME`/etc/

# set job count for makes installing R packages
sudo sed -i "s;^MAKE.*$;MAKE='make -j 1';" `R RHOME`/etc/Renviron

# Test Java
sudo R CMD javareconf

# create empty library
R --no-save < `R RHOME`/etc/Rprofile.site

# install the tidyverse
R -e 'install.packages(c("tidyverse", "XML"))'

# Shiny
R -e 'install.packages("shiny")'

# Package development
R -e 'install.packages(c("devtools", "roxygen2"))'

# Authoring
R -e 'install.packages(c("flexdashboard", "bookdown", "tufte", "rticles"))'
R -e 'devtools::install_github("rstudio/bookdown")'
